[package]
name = "ndarray-stats"
version = "0.1.0"
authors = ["Jim Turner <rust@turner.link>"]

[dependencies]
ndarray = "0.12"
noisy_float = "0.1"
num-traits = "0.2"
rand = "0.5"

[dev-dependencies]
quickcheck = "0.7"
ndarray-rand = "0.8"

[patch.crates-io]
ndarray = { git = "https://github.com/jturner314/ndarray.git", branch = "master" }
noisy_float = { git = "https://github.com/SergiusIW/noisy_float-rs.git", rev = "c33a94803987475bbd205c9ff5a697af533f9a17" }
ndarray = { git = "https://github.com/bluss/ndarray.git", branch = "master" } 