[package]
name = "ndarray-stats"
version = "0.1.0"
authors = ["Jim Turner <rust@turner.link>", "LukeMathWalker <lpalmieri@contact.com>"]

license = "MIT/Apache-2.0"

repository = "https://github.com/jturner314/ndarray-stats"
documentation = "https://docs.rs/ndarray-stats/"

description = "Statistical routines for ArrayBase, the n-dimensional array data structure provided by ndarray."

keywords = ["array", "data-structure", "multidimensional", "statistics", "matrix", "ndarray"]
categories = ["data-structures", "science"]

[dependencies]
ndarray = "0.12"
noisy_float = "0.1"
num-traits = "0.2"
rand = "0.5"
itertools = { version = "0.7.0", default-features = false }

[dev-dependencies]
quickcheck = "0.7"
ndarray-rand = "0.8"

[patch.crates-io]
ndarray = { git = "https://github.com/rust-ndarray/ndarray.git", branch = "master" }
